travis:
  secure:
    BINSTAR_TOKEN: NxQEuTSbt0eaB9lYbwq6OC7E1alczVa+zwAMXAZBFcI6bPFy0EwyTsCfJLn9p/Ei0ZKY5Bm/5SY8q5A5o2mp4Y7+wM1D1owiWhRUjvKnvhYgaFbvsgvcVdYEN4W0ixqNkt9vJf/HGpvohSeD0AlREI6lqSiMh/tsPINrYgek0zGpcGeOJUcsNfPf4OhND0IP6bUSKNDNnIZ3q3Kwek/MmO+E4QXyFWwYg/d/BR45lJX6suGJjzU35GCPKbL2s0TP6ky+I7yw30t1RjfGWA0LOOUPlw95vSbQXLM/aOve4rPsQSLbUi6W36d5Nct6b+PvOXvka5JvbsO8KdK1nPKxj+Z1BfQ+D/G6KrWyDvc4Y2oHPcsbv2MTlAjrcWEsINtWzrCsZvhWlFlBWDl7LAiuRLcMXK9AnWplonCPQdl8Wt9HS06PYVae9xh6EkH+xy4Glejwvy4LmY1Ek/SO2lWzdpM7yZvc+PA9gX3iA8c5Ab0O8QMfxIPpgVZ5uM93l4pRP5WY1yh9lnWpxqIILpmty/NJqxJo+d0Yob8isV0i4xhUTi8LsCUsDprwTtpmPLhPmthAQOTLrGB3O+vUrdvWdhw3gmNtt1kFr0s+MB3DscfGmCHXu68vkgvGwwKAvL8UQI+H4dzq4pCLr1DIkmqE9EUA7TZn3QJmHQULIRHxphA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
